version: "3"

services:
  postgresql:
    image: postgres
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Database
      PGDATA: ~/postgres_data
    ports:
      - "5432:5432"

#  rabbitmq:
#    image: rabbitmq:4-management
#    container_name: rabbitmq
#    restart: always
#    ports:
#      - "5672:5672"
#      - "15672:15672"

#  mongodb:
#    image: mongo
#    container_name: mongodb
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root
#    ports:
#      - "27017:27017"

#    rabbitmq_worker:
#      build: ./workers/rabbitmq
#      container_name: rabbitmq_worker
#      restart: always

  main:
    build: .
    container_name: fastapi
    restart: always
    ports:
      - "8000:8000"
