name: "FastApi"

services:
  postgresql:
    image: postgres
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Database
    ports:
      - 5432:5432
    networks:
      - app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d Database" ]
      interval: 30s
      timeout: 10s
      retries: 3

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - app
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 30s
      timeout: 10s
      retries: 3

#  mongodb:
#    image: mongo
#    container_name: mongodb
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root
#    ports:
#      - 27017:27017
#    networks:
#      - app

  rabbitmq_worker:
    build: ./workers/rabbitmq
    container_name: rabbitmq_worker
    restart: always
    networks:
      - app
    volumes:
      - ./app/:/app/app
      - ./config.py:/app/config.py
      - ./.env:/app/.env
    depends_on:
      rabbitmq:
        condition: service_healthy

  main:
    build: .
    container_name: fastapi
    restart: always
    ports:
      - 8000:8000
    networks:
      - app
    depends_on:
      postgresql:
          condition: service_healthy
      rabbitmq:
        condition: service_healthy

networks:
  app:
    driver: bridge
