version: "3"

services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

#  mongo:
#    image: mongo
#    container_name: mongodb
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root
#    ports:
#      - "27017:27017"

  main:
    build: .
    container_name: fastapi
    restart: always
    ports:
      - "8000:8000"

  rabbitmq_worker:
    build: ./workers/rabbitmq
    container_name: rabbitmq_worker
    restart: always
    volumes:
      -
